package com.technews.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;

// following 3 are class-level annotations
// makes this a persistable object, so User class can map to a table
@Entity
// specifies properties to be ignores when serializing object to JSON
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
// specifies the name of the table that the class maps to; if not present, table name will be class name by default
@Table(name="user")
public class User {
    // instance variable-level annotations
    // sets the identifying key to be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    private String username;
    // ensures emails are unique
    @Column(unique = true)
    private String email;
    private String password;
    // signals to Spring Data JPA that this data does not persist to the database
    @Transient
    boolean loggedIn;

    @OneToMany(mappedBy = "userId", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<Post> posts;
    
    // need to use lazy fetch to resolve multiple bags exception
    @OneToMany(mappedBy = "userId", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Vote> votes;

    @OneToMany(mappedBy = "userId", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Comment> comments;
}
